#!/bin/bash
echo "Cores, MFLOPS" > latency_dst_fmla.csv
for var in $(seq 1 16)
	do perf=$(/home/max/software/Likwid/bin/likwid-bench -t latency_dst_asimd_fmla_sp -w S0:1GB:$var)
	value=$(grep "MFlops/s:" <<< "$perf" | grep -o "[0-9.]\+")
	echo $value
	echo "$var, $value" >> latency_dst_fmla.csv
done

echo "Cores, MFLOPS" > latency_dst_fmul.csv
for var in $(seq 1 16)
	do perf=$(/home/max/software/Likwid/bin/likwid-bench -t latency_dst_asimd_fmul_sp -w S0:1GB:$var)
	value=$(grep "MFlops/s:" <<< "$perf" | grep -o "[0-9.]\+")
	echo $value
	echo "$var, $value" >> latency_dst_fmul.csv
done
